### ISSUE TITLE
Does not seem to work under Windows 7 x64

### ISSUE THREAD

**Issue by MaximRouiller** [mixu/ghost-render#1]
``` bash
ghost-render --settings .\settings.json --theme .\Casper
ghost-render --settings ./settings.json --theme ./Casper
```

Outputs nothing. Not even errors. File and path exist. Executed as admin or non-admin. Makes no difference.

**Comment by vba** [comment]
Same problem under Win 8 x64

**Comment by mAKEkr** [comment]
using node ./node_modules/ghost-render/bin/ghost-render command

**Comment by mixu** [comment]
happy to accept a PR that fixes this! it's probably some kind of path-related issue

**Comment by MaximRouiller** [comment]
No actions in 2 years. I'm closing this.
